[package]
name = "maskedlm"
version = "0.1.0"
edition = "2018"
description = '''
sample maskedlm
'''
license = "xxx"
repository = ""


[dependencies]
tokenizers = "0.10.1"
tract-onnx = "0.15.3"
console_error_panic_hook = "0.1.6"

